language: go
go:
  - 1.10.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
go_import_path: bldy.build/build
install:
  - go get -v -t -d bldy.build/build/...
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
