language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master
compiler: clang
sudo: required
services:
  - docker
matrix:
  allow_failures:
    - go: master
  fast_finish: true
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq clang
- docker pull debian:jessie
go_import_path: bldy.build/build
install:
  - go get -v -t -d bldy.build/build/...
script:
  - ./src/test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
