// Code generated by "stringer -type Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Newline-1]
	_ = x[Error-2]
	_ = x[Module-3]
	_ = x[Ident-4]
	_ = x[String-5]
}

const _Type_name = "EOFNewlineErrorModuleIdentString"

var _Type_index = [...]uint8{0, 3, 10, 15, 21, 26, 32}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
