name: Bldy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-dir: ${{github.workspace}}/src
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go to source
      run: cd src 

    - name: Get dependencies
      working-directory: ${{env.working-dir}}
      run: |
        go get -v -t -d ./...

    - name: test
      working-directory: ${{env.working-dir}}      
      run: go test -v ./...
