name: Bldy
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    env:
      working-dir: ${{github.workspace}}/src
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ${{env.working-dir}}
      run: |
        go get -v -t -d ./...
    - name: test
      working-directory: ${{env.working-dir}}      
      run: go test -race -coverprofile=coverage -covermode=atomic -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.codecovkey }}
        file: ${{env.working-dir}}/coverage
        fail_ci_if_error: false